### PR TITLE
promo block on mobile

### LINKED ISSUE #30: Promo block on mobile
Text/img ratio is currently not working in promo block, we need a version that also works on mobile

### PR DESCRIPTION
**Pull request by tompahans**

### CODE REVIEW

File: src/blocks/Promo/Promo.js [hunk 1]
```diff
@@ -30,32 +32,27 @@ const PromoMain = styled('div', {
...
-            />
-          )}
-
-          <Box sx={{ display: 'flex', flexDirection: 'column' }}>
+        <Card
+          sx={{
+            display: 'flex',
+            bgcolor: 'secondary.light',
+            flexDirection: alignContent === 'right' ? 'row-reverse' : 'row',
+            '@media(max-width: 900px)': {
```
Comment (mrautenberg) [inline src/blocks/Promo/Promo.js]: please use the theme based breakpoints:   `
[theme.breakpoints.up('SCREENSIZE')]: {
    .................
  },
`

instead of max-width

File: src/blocks/Promo/Promo.js [hunk 2]
```diff
@@ -64,22 +61,24 @@ function Promo(props) {
...
+                  autoPlay: true,
+                  muted: true,
+                  loop: true,
+                  playsInline: true,
+                }
+              : { alt: { name } })}
+            {...mediaProps}
+            sx={{
+              clipPath: imageCircle ? `circle(${circleSettings})` : 0,
+              '@media(max-width: 900px)': {
```
Comment (mrautenberg) [inline src/blocks/Promo/Promo.js]: please use the theme based breakpoints: [theme.breakpoints.up('SCREENSIZE')]: { ................. },

instead of max-width

**Review by mrautenberg — CHANGES_REQUESTED** [review]

**Review by mrautenberg — APPROVED** [review]
